# Generated by Django 2.1.3 on 2018-11-25 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, null=True)),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('level', models.CharField(max_length=20, null=True)),
                ('input_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('input_by', models.ManyToManyField(related_name='class_input_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ManyToManyField(related_name='class_modifiled_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('input_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('input_by', models.ManyToManyField(related_name='employer_input_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ManyToManyField(related_name='employer_modifiled_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('job_description', models.TextField(null=True)),
                ('required_degree', models.CharField(max_length=50, null=True)),
                ('japanese_level', models.CharField(max_length=20, null=True)),
                ('other_requirements', models.TextField(null=True)),
                ('input_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='du_lieu_hoc_vien.Employer')),
                ('input_by', models.ManyToManyField(related_name='job_input_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ManyToManyField(related_name='job_modifiled_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('citizen_id', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('current_japanese_level', models.CharField(max_length=20, null=True)),
                ('input_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('input_by', models.ManyToManyField(related_name='student_input_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ManyToManyField(related_name='student_modifiled_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=50, null=True)),
                ('given_by', models.CharField(max_length=50, null=True)),
                ('field_of_study', models.CharField(max_length=100, null=True)),
                ('input_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('input_by', models.ManyToManyField(related_name='degree_input_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ManyToManyField(related_name='degree_modifiled_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='du_lieu_hoc_vien.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_comment', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('input_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('attended_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='du_lieu_hoc_vien.ClassInfo')),
                ('input_by', models.ManyToManyField(related_name='study_record_input_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ManyToManyField(related_name='study_record_modifiled_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='du_lieu_hoc_vien.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('citizen_id', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('input_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('input_by', models.ManyToManyField(related_name='teacher_input_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ManyToManyField(related_name='teacher_modifiled_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_comment', models.TextField(null=True)),
                ('other_notes', models.TextField(null=True)),
                ('input_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='du_lieu_hoc_vien.Employer')),
                ('input_by', models.ManyToManyField(related_name='work_record_input_by', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='du_lieu_hoc_vien.Jobs')),
                ('modified_by', models.ManyToManyField(related_name='work_record_modifiled_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='du_lieu_hoc_vien.Student')),
            ],
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='du_lieu_hoc_vien.Teacher'),
        ),
    ]
