# Generated by Django 2.1.3 on 2018-11-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('du_lieu_hoc_vien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
