# Generated by Django 2.1.4 on 2019-01-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('du_lieu_hoc_vien', '0003_auto_20190101_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to='du_lieu_hoc_vien.Teacher'),
        ),
    ]
